/**
 *  1. DOM
 *  2. DOM SELECTORS 
 *  3. TRAVERSING THE DOM
 *  4. CREATING ELEMENTS ADD INTO IT AND INSERT INTO THE DOM
 *  5. REMOVING AND REPLACING ELEMENTS
 *  6. CLASSESS AND ATTRIBUTES
 *  7. EVENT LISTENERS, THE EVENT OBJECT
 */