// alert("Mzito Js");
console.table({a: 1, b: 2});
console.error("This is some error");
console.clear();
console.warn("This is some warning");
console.time("Hello");
    console.log("Hello World!");
    console.log("Hello World!");
    console.log("Hello World!");
    console.log("Hello World!");
    console.log("Hello World!");
console.timeEnd("Hello");